"use client";
import style from "../../styles/Homepage.module.css";
import Image from "next/image";
import { useState } from "react";
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
// import required modules
import { Pagination } from "swiper/modules";

const HomePage = () => {
  const [activeAccordion, setActiveAccordion] = useState(null);
  const handleAccordionClick = (index) => {
    setActiveAccordion(index === activeAccordion ? null : index);
  };
  const faqData = [
    {
      question: "What is EasyPrompt",
      answer:
        "Easyprompt.ai is an AI-powered writing tool that generates high-quality content for various purposes, including social media marketing, blog articles, product descriptions, email marketing campaigns, and more.",
    },
    {
      question: "How does Easyprompt work?",
      answer:
        "Easyprompt.ai uses natural language processing (NLP) and machine learning algorithms to analyze your inputs, such as topics, keywords, or prompts, and generate content that is on-topic, engaging, and grammatically correct.",
    },
    {
      question: "Who can use Easyprompt",
      answer:
        "Easyprompt.ai can be used by content creators, marketers, writers, e-commerce businesses, and anyone who needs to produce high-quality written content.",
    },
    {
      question: "Can I Customize the content generated by Easyprompt",
      answer:
        "Yes, Easyprompt.ai allows you to customize the content generated by the tool by editing or rewriting it as you see fit. You can also provide feedback to the tool to improve its performance over time.",
    },
    {
      question: "Is Easyprompt secure?",
      answer:
        "Yes, Easyprompt.ai takes security and privacy very seriously. All data is encrypted and stored securely, and the tool adheres to strict data protection regulations.",
    },
  ];

  const testimonialsData = [
    {
      image: "/Images/maria.jpg",
      fullName: "Maria",
      designation: "Free Lancer",
      ratings: "",
      comment:
        "“ As a non-native English speaker, I was always hesitant to write in English. However, with Easyprompt.ai, I feel more confident and comfortable writing in English.”",
    },
    {
      image: "/Images/maria.jpg",
      fullName: "Sarah",
      designation: "Marketing Manager",
      ratings: "",
      comment:
        "“ Easyprompt.ai has made email marketing campaigns a breeze. The tool generates personalized emails that have helped increase our open and click-through rates.”",
    },
    {
      image: "/Images/maria.jpg",
      fullName: "Peter Johns",
      designation: "Content head at Red Marketing",
      ratings: "",
      comment:
        "“ Easyprompt.ai has completely transformed the way I approach content creation. It has helped me save time and produce high-quality content that I'm proud to share with my audience.”",
    },
    {
      image: "/Images/maria.jpg",
      fullName: "Maria",
      designation: "Free Lancer",
      ratings: "",
      comment:
        "“ As a non-native English speaker, I was always hesitant to write in English. However, with Easyprompt.ai, I feel more confident and comfortable writing in English.”",
    },
  ];

  return (
    <section>
      <div className={style.mainContainer}>
        <div className={style.firstblock}>
          <div>
            <h1>The Ultimate AI Writing Tool For All Your Content Needs!</h1>
            <label>
              With Easyprompt, you can effortlessly create high-quality content
              for your business, blog, or personal use.
            </label>
            <button>Get Started For Free</button>
          </div>
          <div>
            <Image
              src="/Images/Home-bg-image.png"
              alt="Image"
              width={550}
              height={508}
            />
          </div>
        </div>
        <div className={style.secondBlock}>
          <div className={style.InnerAboutBlock}>
            <div>
              <Image
                src="/Images/home-about-sec-image-1.jpg"
                alt="Image0"
                width={391}
                height={373}
              />
              <Image
                src="/Images/home-about-sec-image-0.jpg"
                alt="Image1"
                width={384}
                height={403}
              />
            </div>
            <div>
              <Image
                src="/Images/home-about-sec-image.jpg"
                alt="Image3"
                width={136}
                height={131}
              />
              <Image
                src="/Images/home-about-sec-image-3.jpg"
                alt="Image4"
                width={100}
                height={90}
              />
            </div>
          </div>
          <div>
            <h5>ABOUT US</h5>
            <h3>
              Our powerful AI writing technology generates unique and engaging
              content in seconds, saving you time and effort.
            </h3>
            <label>
              At easyprompt.ai, we are passionate about revolutionizing the
              world of content creation with the power of artificial
              intelligence. Our team of experts in AI technology and content
              creation is dedicated to providing you with the best possible
              writing tool to make your life easier and more efficient.
            </label>
            <div>
              <section>
                <Image
                  src="/Images/about-sec-image.svg"
                  alt="logo"
                  width={50}
                  height={50}
                />
                <div>
                  <h2>100% Customers Satisfaction</h2>
                  <label>
                    Customer satisfaction is & will be always our top priority
                  </label>
                </div>
              </section>
              <section>
                <Image
                  src="/Images/about-sec-image-1.svg"
                  alt="logo"
                  width={50}
                  height={50}
                />

                <div>
                  <h2>Quality Assurance Guarantee</h2>
                  <label>
                    Our tool is designed in a way that you always get unique &
                    engaging content
                  </label>
                </div>
              </section>
            </div>
            <button>Read More</button>
          </div>
        </div>
        <div className={style.FeaturesBlock}>
          <div>
            <h5>FEATURES WE OFFER</h5>
            <h3>
              Our goal is to help businesses and individuals create high-quality
              content.
            </h3>
            <label>
              With easyprompt, we believe that everyone can be a great writer,
              regardless of their experience level. Whether you need blog posts,
              social media captions, or product descriptions, easyprompt has got
              you covered.
            </label>
            <button>VIEW ALL USE CASES</button>
          </div>
          <div>
            <div className={style.FeaturesCard}>
              <span>
                <Image
                  src="/Images/product-descriptions.png"
                  alt="Image"
                  width={40}
                  height={40}
                />
              </span>
              <label>Product Descriptions</label>
              <button>
                <p>Know More</p>
              </button>
            </div>
            <div className={style.FeaturesCard}>
              <span>
                <Image
                  src="/Images/copy-writing.png"
                  alt="Image"
                  width={40}
                  height={40}
                />
              </span>
              <label>Website Copies</label>
              <button>
                <p>Know More</p>
              </button>
            </div>
            <div className={style.FeaturesCard}>
              <span>
                <Image
                  src="/Images/email-services.png"
                  alt="Image"
                  width={40}
                  height={40}
                />
              </span>
              <label>Emails</label>
              <button>
                <p>Know More</p>
              </button>
            </div>
            <div className={style.FeaturesCard}>
              <span>
                <Image
                  src="/Images/services-sec-home-page-1.png"
                  alt="Image"
                  width={40}
                  height={40}
                />
              </span>
              <label>Blog Idea & Writing</label>
              <button>
                <p>Know More</p>
              </button>
            </div>
          </div>
        </div>
        {/* Why chooseUs Block */}
        <div className={style.why_choose_us}>
          <div>
            <Image
              src="/Images/home-why-choose-us-image 1.png"
              alt="Profile pic"
              width={740.372}
              height={582.613}
            />
          </div>
          <div>
            <h5>WHY CHOOSE US</h5>
            <h3>Get Closer Look How Business Develop in AI Data Analysis</h3>
            <label>
              Our platform is designed to be user-friendly and intuitive, so you
              dont need to be a professional writer or have any technical
              expertise to use it. Simply input your topic, and Easyprompt will
              do the rest.
            </label>
            <div>
              <li>AI-Powered Technology</li>
              <li>Easy To Use</li>
              <li>Cost Effective</li>
              <li>Personalized Dashboard</li>
              <li>SEO Optimized Content</li>
              <li>75+ Languages Supported</li>
            </div>
          </div>
        </div>
        {/* CASE STUDY */}
        <div className={style.CaseStudy}>
          <h5>CASE STUDY</h5>
          <h3>Explore Our Case Studies</h3>
          <div>
            <div className={style.image_container}>
              <Image
                src="/Images/Home-case-studeis-image.jpg"
                alt="Image"
                width={350}
                height={400}
              />
              <div className={style.image_text}>
                <h2>Small Business</h2>
                <label>Janes Boutique</label>
              </div>
            </div>
            <div className={style.image_container}>
              <Image
                src="/Images/Home-case-study-image1.jpg"
                alt="Image"
                width={350}
                height={400}
              />
              <div className={style.image_text}>
                <h2>Marketing Agency</h2>
                <label>Red Marketing</label>
              </div>
            </div>
            <div className={style.image_container}>
              <Image
                src="/Images/Home-case-study-image2.jpg"
                alt="Image"
                width={350}
                height={400}
              />
              <div className={style.image_text}>
                <h2>E-commerce</h2>
                <label>TechSmart</label>
              </div>
            </div>
          </div>
        </div>
        {/* Testimonials */}
        <div className={style.Testimonials}>
          <h5>TESTIMONIALS</h5>
          <h3>Hear it from Our Clients</h3>
          {/* {
            testimonialsData.map((item)=>{
              
            })
          } */}

          <div>
            <Swiper
              slidesPerView={3}
              spaceBetween={10}
              slidesPerGroup={3}
              pagination={{
                clickable: true,
              }}
              modules={[Pagination]}
              loop={true}
              autoplay={{
                delay: 100,
                disableOnInteraction: false,
              }}
              className="mySwiper"
            >
              {testimonialsData.map((testimonial, index) => (
                <SwiperSlide key={index}>
                  <div className={style.TestimonialCards}>
                    <div>
                      <Image
                        src="/Images/quotes.png"
                        alt="logo"
                        width={40}
                        height={40}
                      />
                    </div>
                    <Image
                      src={testimonial.image}
                      alt="image"
                      width={60}
                      height={60}
                    />
                    <h2>{testimonial.fullName}</h2>
                    <h6>{testimonial.designation}</h6>
                    <label>{testimonial.comment}</label>
                  </div>
                </SwiperSlide>
              ))}
              {/* <SwiperSlide>
                {" "}
                <div className={style.TestimonialCards}>
                  <div>
                    <Image
                      src="/Images/quotes.png"
                      alt="logo"
                      width={40}
                      height={40}
                    />
                  </div>
                  <Image
                    src="/Images/maria.jpg"
                    alt="image"
                    width={20}
                    height={20}
                  />
                  <h2>Maria</h2>
                  <h6>Free Lancer</h6>
                  <label>
                    &#8220; As a non-native English speaker, I was always
                    hesitant to write in English. However, with Easyprompt.ai, I
                    feel more confident and comfortable writing in English.&#34;
                  </label>
                </div>
                <div className={style.TestimonialCards}>
                  <div>
                    <Image
                      src="/Images/quotes.png"
                      alt="logo"
                      width={40}
                      height={40}
                    />
                  </div>
                  <Image
                    src="/Images/maria.jpg"
                    alt="image"
                    width={20}
                    height={20}
                  />
                  <h2>Maria</h2>
                  <h6>Free Lancer</h6>
                  <label>
                    &#8220; As a non-native English speaker, I was always
                    hesitant to write in English. However, with Easyprompt.ai, I
                    feel more confident and comfortable writing in English.&#34;
                  </label>
                </div>
                <div className={style.TestimonialCards}>
                  <div>
                    <Image
                      src="/Images/quotes.png"
                      alt="logo"
                      width={40}
                      height={40}
                    />
                  </div>
                  <Image
                    src="/Images/maria.jpg"
                    alt="image"
                    width={20}
                    height={20}
                  />
                  <h2>Maria</h2>
                  <h6>Free Lancer</h6>
                  <label>
                    &#8220; As a non-native English speaker, I was always
                    hesitant to write in English. However, with Easyprompt.ai, I
                    feel more confident and comfortable writing in English.&#34;
                  </label>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className={style.TestimonialCards}>
                  <div>
                    <Image
                      src="/Images/quotes.png"
                      alt="logo"
                      width={40}
                      height={40}
                    />
                  </div>
                  <Image
                    src="/Images/maria.jpg"
                    alt="image"
                    width={40}
                    height={40}
                  />
                  <h2>Maria</h2>
                  <h6>Free Lancer</h6>
                  <label>
                    &#8220; As a non-native English speaker, I was always
                    hesitant to write in English. However, with Easyprompt.ai, I
                    feel more confident and comfortable writing in English.&#34;
                  </label>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className={style.TestimonialCards}>
                  <div>
                    <Image
                      src="/Images/quotes.png"
                      alt="logo"
                      width={40}
                      height={40}
                    />
                  </div>
                  <Image
                    src="/Images/maria.jpg"
                    alt="image"
                    width={40}
                    height={40}
                  />
                  <h2>Maria</h2>
                  <h6>Free Lancer</h6>
                  <label>
                    &#8220; As a non-native English speaker, I was always
                    hesitant to write in English. However, with Easyprompt.ai, I
                    feel more confident and comfortable writing in English.&#34;
                  </label>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className={style.TestimonialCards}>
                  <div>
                    <Image
                      src="/Images/quotes.png"
                      alt="logo"
                      width={40}
                      height={40}
                    />
                  </div>
                  <Image
                    src="/Images/maria.jpg"
                    alt="image"
                    width={40}
                    height={40}
                  />
                  <h2>Maria</h2>
                  <h6>Free Lancer</h6>
                  <label>
                    &#8220; As a non-native English speaker, I was always
                    hesitant to write in English. However, with Easyprompt.ai, I
                    feel more confident and comfortable writing in English.&#34;
                  </label>
                </div>
              </SwiperSlide>
              <SwiperSlide>Slide 5</SwiperSlide>
              <SwiperSlide>Slide 6</SwiperSlide>
              <SwiperSlide>Slide 7</SwiperSlide>
              <SwiperSlide>Slide 8</SwiperSlide>
              <SwiperSlide>Slide 9</SwiperSlide> */}
            </Swiper>
          </div>
        </div>
        {/* FAQ section */}
        <div className={style.FAQSection}>
          <div>
            <h5>FAQ&apos;S</h5>
            <h3>Frequently Asked Questions</h3>
            <div className={style.AccordionContainer}>
              {faqData.map((item, index) => (
                <div
                  key={index}
                  className={`${style.AccordionItem} ${
                    index === activeAccordion ? style.Active : ""
                  }`}
                  onClick={() => handleAccordionClick(index)}
                >
                  <h3>{item.question}</h3>
                  <div
                    className={`${style.AccordionContent} ${
                      index === activeAccordion ? style.Show : ""
                    }`}
                  >
                    <p>{item.answer}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className={style.FAQSCard}>
            <h3>Need any Help!</h3>
            <label>
              Have any questions? Need more Help ? We are always here to help
              you. Submit the simple forum below, We&apos;ll get back to you.
            </label>
            <div>
              <input type="text" placeholder="Your Name:" required />
              <input type="email" placeholder="Your Email:" required />
              <input type="mobile" placeholder="Phone:" required />
              <textarea placeholder="Message:" rows={4} />
              <button>Submit Now</button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HomePage;
